# **Discritization & Binning Method**

###**Convert Nominal Attributes to Dummy Variables**

Importing required libraries

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('weather.csv')
df

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

Converting windy attribute to dummy variable

In [ ]:
windy_true = []
windy_false = []
for val in df['windy']:
    if val:
        windy_true.append(1) # assigning value 1 if atmostphere is windy
        windy_false.append(0)
    else:
        windy_true.append(0) # assigning value 0 if atmostphere is not windy
        windy_false.append(1)
print(windy_true)
print(windy_false)

[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]
[1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0]


Converting outlook attribute to dummy variable

In [ ]:
outlook_sunny = []
outlook_overcast = []
outlook_rainy = []
outlook_num = []
for val in df['outlook']:
    if val == 'sunny':
        outlook_sunny.append(1)
        outlook_overcast.append(0)
        outlook_rainy.append(0)
        outlook_num.append(1)
    elif val == 'overcast':
        outlook_sunny.append(0)
        outlook_overcast.append(1)
        outlook_rainy.append(0)
        outlook_num.append(2) 
    else:
        outlook_sunny.append(0)
        outlook_overcast.append(0)
        outlook_rainy.append(1)
        outlook_num.append(3)
print(outlook_sunny)
print(outlook_overcast)
print(outlook_rainy)
print(outlook_num)

[1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1]
[1, 1, 2, 3, 3, 3, 2, 1, 1, 3, 1, 2, 2, 3]


Converting play attribute to dummy variable

In [ ]:
play_true = []
play_false = []
for val in df['play']:
    if val == 'yes':
        play_true.append(1)
        play_false.append(0)
    else:
        play_true.append(0)
        play_false.append(1)
print(play_true)
print(play_false)

[0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]
[1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]


In [ ]:
df['windy_false'] = windy_false
df['windy_true'] = windy_true
df['sunny'] = outlook_sunny
df['overcast'] = outlook_overcast
df['rainy'] = outlook_rainy
df['outlook_num'] = outlook_num
df['play_yes'] = play_true
df['play_no'] = play_false

In [ ]:
df = df.drop(['outlook', 'windy', 'play'], axis=1)
df

temperature  humidity  windy_false  ...  outlook_num  play_yes  play_no
0            85        85            1  ...            1         0        1
1            80        90            0  ...            1         0        1
2            83        86            1  ...            2         1        0
3            70        96            1  ...            3         1        0
4            68        80            1  ...            3         1        0
5            65        70            0  ...            3         0        1
6            64        65            0  ...            2         1        0
7            72        95            1  ...            1         0        1
8            69        70            1  ...            1         1        0
9            75        80            1  ...            3         1        0
10           75        70            0  ...            1         1        0
11           72        90            0  ...            2         1        0
12           81        75            1  ...            2         1        0
13           71        91            0  ...            3         0        1

[14 rows x 10 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  14 non-null     int64
 1   humidity     14 non-null     int64
 2   windy_false  14 non-null     int64
 3   windy_true   14 non-null     int64
 4   sunny        14 non-null     int64
 5   overcast     14 non-null     int64
 6   rainy        14 non-null     int64
 7   outlook_num  14 non-null     int64
 8   play_yes     14 non-null     int64
 9   play_no      14 non-null     int64
dtypes: int64(10)
memory usage: 1.2 KB


###**Binning Method**

In [ ]:
import numpy as np

In [ ]:
df1 = pd.read_csv('diabetes.csv')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   preg    768 non-null    int64  
 1   plas    768 non-null    int64  
 2   pres    768 non-null    int64  
 3   skin    768 non-null    int64  
 4   insu    768 non-null    int64  
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64  
 8   class   768 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB


In [ ]:
df1.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0     6   148    72    35     0  33.6  0.627   50  tested_positive
1     1    85    66    29     0  26.6  0.351   31  tested_negative
2     8   183    64     0     0  23.3  0.672   32  tested_positive
3     1    89    66    23    94  28.1  0.167   21  tested_negative
4     0   137    40    35   168  43.1  2.288   33  tested_positive

Implementing binning method

Applying binning on mass attribute

In [ ]:
val = np.array(df1['mass'])
print(val)

[33.6 26.6 23.3 28.1 43.1 25.6 31.  35.3 30.5 30.  37.6 38.  27.1 30.1
 25.8 30.  45.8 29.6 43.3 34.6 39.3 35.4 39.8 29.  36.6 31.1 39.4 23.2
 22.2 34.1 36.  31.6 24.8 19.9 27.6 24.  33.2 32.9 38.2 37.1 34.  40.2
 22.7 45.4 27.4 42.  29.7 28.  39.1 30.  19.4 24.2 24.4 33.7 34.7 23.
 37.7 46.8 40.5 41.5 30.  32.9 25.  25.4 32.8 29.  32.5 42.7 19.6 28.9
 32.9 28.6 43.4 35.1 32.  24.7 32.6 37.7 43.2 25.  22.4 30.  29.3 24.6
 48.8 32.4 36.6 38.5 37.1 26.5 19.1 32.  46.7 23.8 24.7 33.9 31.6 20.4
 28.7 49.7 39.  26.1 22.5 26.6 39.6 28.7 22.4 29.5 34.3 37.4 33.3 34.
 31.2 34.  30.5 31.2 34.  33.7 28.2 23.2 53.2 34.2 33.6 26.8 33.3 55.
 42.9 33.3 34.5 27.9 29.7 33.3 34.5 38.3 21.1 33.8 30.8 28.7 31.2 36.9
 21.1 39.5 32.5 32.4 32.8 30.  32.8 30.5 33.7 27.3 37.4 21.9 34.3 40.6
 47.9 50.  24.6 25.2 29.  40.9 29.7 37.2 44.2 29.7 31.6 29.9 32.5 29.6
 31.9 28.4 30.8 35.4 28.9 43.5 29.7 32.7 31.2 67.1 45.  39.1 23.2 34.9
 27.7 26.8 27.6 35.9 30.1 32.  27.9 31.6 22.6 33.1 30.4 52.3 24.4 39.4
 24.3 22.

In [ ]:
val.sort()
print(val)

[18.2 18.2 18.2 18.4 19.1 19.3 19.4 19.5 19.5 19.6 19.6 19.6 19.9 20.
 20.1 20.4 20.4 20.8 20.8 21.  21.  21.1 21.1 21.1 21.1 21.2 21.7 21.8
 21.8 21.8 21.8 21.8 21.9 21.9 21.9 22.1 22.1 22.2 22.2 22.3 22.4 22.4
 22.5 22.5 22.5 22.6 22.6 22.7 22.9 22.9 23.  23.  23.1 23.1 23.1 23.1
 23.2 23.2 23.2 23.3 23.3 23.4 23.5 23.5 23.5 23.6 23.6 23.6 23.7 23.7
 23.8 23.8 23.9 23.9 24.  24.  24.  24.  24.1 24.2 24.2 24.2 24.2 24.2
 24.2 24.3 24.3 24.3 24.3 24.4 24.4 24.4 24.5 24.6 24.6 24.6 24.6 24.7
 24.7 24.7 24.7 24.7 24.8 24.8 24.8 24.9 25.  25.  25.  25.  25.  25.
 25.1 25.1 25.1 25.2 25.2 25.2 25.2 25.2 25.2 25.3 25.3 25.4 25.4 25.4
 25.4 25.5 25.5 25.6 25.6 25.6 25.6 25.6 25.6 25.8 25.8 25.9 25.9 25.9
 25.9 25.9 25.9 25.9 26.  26.  26.  26.  26.1 26.1 26.1 26.2 26.2 26.2
 26.2 26.3 26.4 26.4 26.4 26.5 26.5 26.5 26.6 26.6 26.6 26.6 26.7 26.8
 26.8 26.8 26.8 26.9 27.  27.  27.1 27.1 27.1 27.2 27.2 27.3 27.3 27.3
 27.3 27.4 27.4 27.4 27.4 27.4 27.5 27.5 27.5 27.5 27.5 27.6 27.6 27.6
 27.6 27

Initializing bins

In [ ]:
bin_size = 8
bin = np.zeros((int(len(val)/bin_size), bin_size))
bin.shape

(96, 8)

In [ ]:
for i in range(0,len(val),bin_size):
    sum=0
    for j in range(bin_size):
        sum = sum + val[j+i]
    avg = sum/bin_size
    for j in range(bin_size):
        bin[int(i/bin_size), j] = avg
print(bin.shape)

(96, 8)


In [ ]:
print(bin)

[[18.7875 18.7875 18.7875 18.7875 18.7875 18.7875 18.7875 18.7875]
 [19.8375 19.8375 19.8375 19.8375 19.8375 19.8375 19.8375 19.8375]
 [20.9125 20.9125 20.9125 20.9125 20.9125 20.9125 20.9125 20.9125]
 [21.625  21.625  21.625  21.625  21.625  21.625  21.625  21.625 ]
 [22.075  22.075  22.075  22.075  22.075  22.075  22.075  22.075 ]
 [22.525  22.525  22.525  22.525  22.525  22.525  22.525  22.525 ]
 [23.025  23.025  23.025  23.025  23.025  23.025  23.025  23.025 ]
 [23.325  23.325  23.325  23.325  23.325  23.325  23.325  23.325 ]
 [23.6625 23.6625 23.6625 23.6625 23.6625 23.6625 23.6625 23.6625]
 [24.0125 24.0125 24.0125 24.0125 24.0125 24.0125 24.0125 24.0125]
 [24.2375 24.2375 24.2375 24.2375 24.2375 24.2375 24.2375 24.2375]
 [24.475  24.475  24.475  24.475  24.475  24.475  24.475  24.475 ]
 [24.7125 24.7125 24.7125 24.7125 24.7125 24.7125 24.7125 24.7125]
 [24.9625 24.9625 24.9625 24.9625 24.9625 24.9625 24.9625 24.9625]
 [25.1625 25.1625 25.1625 25.1625 25.1625 25.1625 25.1625 25.1

Applying Binnig on Age attribute

In [ ]:
val2 = np.array(df1['age'])
print(val2)

[50 31 32 21 33 30 26 29 53 54 30 34 57 59 51 32 31 31 33 32 27 50 41 29
 51 41 43 22 57 38 60 28 22 28 45 33 35 46 27 56 26 37 48 54 40 25 29 22
 31 24 22 26 30 58 42 21 41 31 44 22 21 39 36 24 42 32 38 54 25 27 28 26
 42 23 22 22 41 27 26 24 22 22 36 22 37 27 45 26 43 24 21 34 42 60 21 40
 24 22 23 31 33 22 21 24 27 21 27 37 25 24 24 46 23 25 39 61 38 25 22 21
 25 24 23 69 23 26 30 23 40 62 33 33 30 39 26 31 21 22 29 28 55 38 22 42
 23 21 41 34 65 22 24 37 42 23 43 36 21 23 22 47 36 45 27 21 32 41 22 34
 29 29 36 29 25 23 33 36 42 26 47 37 32 23 21 27 40 41 60 33 31 25 21 40
 36 40 42 29 21 23 26 29 21 28 32 27 55 27 57 52 21 41 25 24 60 24 36 38
 25 32 32 41 21 66 37 61 26 22 26 24 31 24 22 46 22 29 23 26 51 23 32 27
 21 22 22 33 29 49 41 23 34 23 42 27 24 25 44 21 30 25 24 51 34 27 24 63
 35 43 25 24 21 28 38 21 40 21 52 25 29 23 57 22 28 39 37 47 52 51 34 29
 26 33 21 25 31 24 65 28 29 24 46 58 30 25 35 28 37 29 47 21 25 30 41 22
 27 25 43 26 30 29 28 59 31 25 36 43 21 24 30 37 23

In [ ]:
val2.sort()
val2

array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25,
       25, 25, 25, 25, 25

Initializing bins

In [ ]:
bin_size_2 = 32
bin2 = np.zeros((int(len(val2)/bin_size_2),bin_size_2))
bin2.shape

(24, 32)

In [ ]:
for i in range(0,len(val2),bin_size_2):
    sum=0
    for j in range(bin_size_2):
        sum = sum + val[j+i]
    avg = sum/bin_size_2
    for j in range(bin_size_2):
        bin2[int(i/bin_size_2), j] = avg
print(bin2.shape)

(24, 32)


In [ ]:
bin2

array([[20.290625, 20.290625, 20.290625, 20.290625, 20.290625, 20.290625,
        20.290625, 20.290625, 20.290625, 20.290625, 20.290625, 20.290625,
        20.290625, 20.290625, 20.290625, 20.290625, 20.290625, 20.290625,
        20.290625, 20.290625, 20.290625, 20.290625, 20.290625, 20.290625,
        20.290625, 20.290625, 20.290625, 20.290625, 20.290625, 20.290625,
        20.290625, 20.290625],
       [22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  ,
        22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  ,
        22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  ,
        22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  ,
        22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  , 22.7375  ,
        22.7375  , 22.7375  ],
       [24.096875, 24.096875, 24.096875, 24.096875, 24.096875, 24.096875,
        24.096875, 24.096875, 24.096875, 24.096875, 24.096875, 24.096875,
        24.096875, 24.096875, 24.096875, 24.096875